name: Verify Bearer Token Secret

on:
  workflow_dispatch:

jobs:
  verify-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Bearer Token
        run: echo "Bearer Token: ${{ secrets.Bearer_Token }}"
