name: Update Bearer Token

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Get Bearer Token
        id: get_token
        run: |
          response=$(curl -s -X POST https://cognito-idp.eu-west-1.amazonaws.com/ \
            -H "Content-Type: application/json" \
            -d '{
              "AuthParameters" : {
                "USERNAME" : "'"${{ secrets.COGNITO_USERNAME }}"'",
                "PASSWORD" : "'"${{ secrets.COGNITO_PASSWORD }}"'"
              },
              "AuthFlow" : "USER_PASSWORD_AUTH",
              "ClientId" : "'"${{ secrets.COGNITO_CLIENT_ID }}"'"
            }')
          token=$(echo $response | jq -r '.AuthenticationResult.IdToken')
          echo "BEARER_TOKEN=$token" >> $GITHUB_ENV

      - name: Set GitHub Secret
        run: |
          gh api \
            -H "Accept: application/vnd.github.v3+json" \
            -X PUT \
            /repos/$GITHUB_REPOSITORY/actions/secrets/Bearer_Token \
            -f encrypted_value=$(echo -n ${{ env.BEARER_TOKEN }} | base64) \
            -f key_id=$(gh api /repos/$GITHUB_REPOSITORY/actions/secrets/public-key | jq -r '.key_id')
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          BEARER_TOKEN: ${{ env.BEARER_TOKEN }}
