name: Update Bearer Token

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Get Bearer Token
        id: get_token
        run: |
          response=$(curl -s -X POST https://cognito-idp.eu-west-1.amazonaws.com/ \
            -H "Content-Type: application/json" \
            -d '{
              "AuthParameters" : {
                "USERNAME" : "'"${{ secrets.COGNITO_USERNAME }}"'",
                "PASSWORD" : "'"${{ secrets.COGNITO_PASSWORD }}"'"
              },
              "AuthFlow" : "USER_PASSWORD_AUTH",
              "ClientId" : "'"${{ secrets.COGNITO_CLIENT_ID }}"'"
            }')
          echo "Response: $response"
          token=$(echo $response | jq -r '.AuthenticationResult.IdToken')
          if [ -z "$token" ]; then
            echo "Failed to obtain bearer token"
            exit 1
          fi
          echo "BEARER_TOKEN=$token" >> $GITHUB_ENV

      - name: Get Repository Public Key
        id: get_public_key
        run: |
          public_key=$(gh api /repos/$GITHUB_REPOSITORY/actions/secrets/public-key | jq -r '.key')
          key_id=$(gh api /repos/$GITHUB_REPOSITORY/actions/secrets/public-key | jq -r '.key_id')
          echo "PUBLIC_KEY=$public_key" >> $GITHUB_ENV
          echo "KEY_ID=$key_id" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Encrypt and Set GitHub Secret
        run: |
          echo "${{ env.PUBLIC_KEY }}" | base64 -d > public_key.pem
          encrypted_value=$(echo -n "${{ env.BEARER_TOKEN }}" | openssl pkeyutl -encrypt -pubin -inkey public_key.pem | base64)
          echo "Encrypted Value: $encrypted_value"
          gh api \
            -H "Accept: application/vnd.github.v3+json" \
            -X PUT \
            /repos/$GITHUB_REPOSITORY/actions/secrets/Bearer_Token \
            -f encrypted_value="$encrypted_value" \
            -f key_id="${{ env.KEY_ID }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          PUBLIC_KEY: ${{ env.PUBLIC_KEY }}
          BEARER_TOKEN: ${{ env.BEARER_TOKEN }}
          KEY_ID: ${{ env.KEY_ID }}
