name: Update Bearer Token

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Get Bearer Token
        id: get_token
        run: |
          response=$(curl -s -X POST https://cognito-idp.eu-west-1.amazonaws.com/ \
            -H "Content-Type: application/x-amz-json-1.1" \
            -H "X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth" \
            -d '{
              "AuthParameters" : {
                "USERNAME" : "'"${{ secrets.COGNITO_USERNAME }}"'",
                "PASSWORD" : "'"${{ secrets.COGNITO_PASSWORD }}"'"
              },
              "AuthFlow" : "USER_PASSWORD_AUTH",
              "ClientId" : "'"${{ secrets.COGNITO_CLIENT_ID }}"'"
            }')
          echo "Response: $response"
          token=$(echo $response | jq -r '.AuthenticationResult.IdToken')
          if [ -z "$token" ]; then
            echo "Failed to obtain bearer token"
            exit 1
          fi
          echo "BEARER_TOKEN=$token" >> $GITHUB_ENV
          echo "::add-mask::$token" # Mask the token in logs for security

      - name: Get Public Key
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Fetching the latest public key..."
          PUBLIC_KEY=$(curl -s -X GET \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/lyuboslav2406/status-xrm/actions/secrets/public-key | jq -r '.key')

      - name: Update Repository Secret
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          PUBLIC_KEY: $PUBLIC_KEY
        run: |
          echo "Updating repository secret..."
          ENCRYPTED_TOKEN=$(echo -n $BEARER_TOKEN | openssl pkeyutl -encrypt -pubin -inkey <(echo "$PUBLIC_KEY") | base64 -w 0)
          curl -X PUT \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/lyuboslav2406/status-xrm/actions/secrets/BEARER_TOKEN \
            -d "{\"encrypted_value\":\"$ENCRYPTED_TOKEN\",\"key_id\":\"\"}"
